export const languages = {
    'C' : 'C',
    'C++'	: 'CPP',
    'C++11'	: 'CPP11',
    'C++14'	: 'CPP14',
    'C#'	: 'CSHARP',
    'Go'	: 'GO',
    'Java'	: 'JAVA',
    'Java 8'	: 'JAVA8',
    'JavaScript'	: 'JAVASCRIPT',
    'Kotlin'	: 'KOTLIN',
    'Objective C'	: 'OBJECTIVEC',
    'PHP'	: 'PHP',
    'Python 2'	: 'PYTHON',
    'Python 3'	: 'PYTHON3',
    'R'	: 'R',
    'Ruby'	: 'RUBY',
    'Rust'	: 'RUST',
    'Scala'	: 'SCALA',
    'Swift'	: 'SWIFT'
}